### ISSUE TITLE
Pay button appearance defaults to GPay no matter what button type is passed.

### ISSUE THREAD

**Issue by zas9vf** [google-pay/compose-pay-button#46]
Hey team! 

I'm trying to use the PayButton in my project but no matter what `ButtonType` is passed to it, it still shows up the way it does in the screenshot below. 

<img width="344" alt="image" src="https://github.com/google-pay/compose-pay-button/assets/3465051/e0a7b7c8-1720-40ed-a3e3-d5e96b784c57">

Would the info in the `allowedPaymentMethods` string param affect the appearance of the button in this way by any chance?

**Comment by dmengelt** [comment]
yes. make sure your `allowedPaymentMethods` payload is correct. if we cannot parse `allowedPaymentMethods` we fallback to the generic "GPay" logo.

**Comment by zas9vf** [comment]
thanks for your quick response @dmengelt . That's strange because my payload looks correct! Do you mind giving it a look below to see if i missed anything?

```
	val allowedPaymentMethods = """
            [
              {
                "type": "CARD",
                "parameters": {
                  "allowedAuthMethods": ["PAN_ONLY", "CRYPTOGRAM_3DS"],
                  "allowedCardNetworks": ["AMEX", "DISCOVER", "JCB", "MASTERCARD", "VISA"]
                },
                "tokenizationSpecification": {
                  "type": "PAYMENT_GATEWAY",
                  "parameters": {
										"gateway": "stripe",
										"stripe:version": "2018-10-31",
										"stripe:publishableKey": "<PublishableKey_Key>"
                  }
                }
              }
            ]
        """.trimIndent()

```

**Comment by dmengelt** [comment]
works for me. do you use an emulator with Google Play services enabled?

**Comment by zas9vf** [comment]
i was NOT on a Google Play services enabled device 🤦‍♂️. That did it! 

<img width="395" alt="image" src="https://github.com/google-pay/compose-pay-button/assets/3465051/9c8d8696-ee39-4815-b4c4-86948329fcc6">

Thank you for your help @dmengelt

**Comment by dmengelt** [comment]
anytime!
