### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by rasmusandersson5** [google-pay/compose-pay-button#5]
Is there a way to set the button to disabled?

Standard buttons have the enabled param to control this
```
@Composable
fun Button(
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    enabled: Boolean = true,
    ...
```

Our use case involves showing terms & conditions that needs to be accepted before clicking on GooglePay

**Comment by dmengelt** [comment]
@rasmusandersson5 good point. at the moment there is no disabled state. however, we are looking into this...

**Comment by dmengelt** [comment]
Disabled state is available with the 0.1.3 release

**Comment by cmargonis** [comment]
Hello @dmengelt , thanks for this library!

My question is whether having the Google Pay button in a disabled state is allowed by Google or not.
Reading the [brand guidelines on the topic](https://developers.google.com/pay/api/android/guides/brand-guidelines#dos-and-donts), it mentions in the `Don't` section:
> Create your own Google Pay buttons or alter the font, color, button radius, or padding within the button in any way

So based on the above, its color is being altered. Is this something ok?

**Comment by dmengelt** [comment]
Hi @cmargonis Disabled state is a special case 😉. If you are facing issues getting the approval, let me know.

**Comment by cmargonis** [comment]
Thank you, this is amazing 😊
