### ISSUE TITLE
Dark/Light theme

### ISSUE THREAD

**Issue by rasmusandersson5** [google-pay/compose-pay-button#79]
Hi!

I'm wondering how Dark/Light theme should be used.
Should the button theme be selected based on the device Dark/Light theme state, or will the button handle this itself?
When I look around in various documentation it looks like the button should be white when device is in dark mode, but the button dark theme does not handle that - hence the question if I'm expected to manually change to `theme=Light` when device is in dark mode?

**Comment by dmengelt** [comment]
Hi @rasmusandersson5 

Right now, we don't check the device theme to set on the button, developers would have to change it themselves. This was done because not every app has a light/dark theme, so we won't override the user selection.
